{% set name = "fitsverify" %}
{% set version = "4.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://heasarc.gsfc.nasa.gov/docs/software/ftools/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c45e803a7e0edbcb7d13918615bae6361d2b333c292b849c509ec9bebdb18b4

build:
  number: 6
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
  host:
    - bzip2
    - cfitsio
    - libcurl

test:
  commands:
    - fitsverify -h

about:
  home: https://heasarc.gsfc.nasa.gov/docs/software/ftools/fitsverify
  license: MIT
  license_file: {{ RECIPE_DIR }}/license.txt
  summary: A FITS File Format-Verification Tool
  description: |
    Fitsverify is a computer program that rigorously checks whether a FITS
    (Flexible Image Transport System) data file conforms to the requirements
    defined in Version 3.0 of the FITS Standard document.

extra:
  recipe-maintainers:
    - jhunkeler
    - bgannon2
    - stsci-hack
    - mdlpstsci
    - nden
